package com.example.smartspendai.ui.report;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Typeface;
import android.graphics.pdf.PdfDocument;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Draws a simple one-page PDF report using Android's built-in
 * android.graphics.pdf.PdfDocument — no external library (like iText)
 * needed, which keeps the app's dependency footprint small.
 *
 * Page size: 595 x 842 "points" (1/72 inch), which is standard A4 —
 * matches what most PDF viewers/printers expect by default.
 */
public class PdfReportGenerator {

    private static final int PAGE_WIDTH = 595;
    private static final int PAGE_HEIGHT = 842;

    public static File generate(Context context, String periodLabel, double total,
                                 List<Map.Entry<String, Double>> categoryTotals) throws IOException {

        PdfDocument document = new PdfDocument();
        PdfDocument.PageInfo pageInfo = new PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, 1).create();
        PdfDocument.Page page = document.startPage(pageInfo);
        Canvas canvas = page.getCanvas();

        Paint titlePaint = new Paint();
        titlePaint.setColor(Color.BLACK);
        titlePaint.setTextSize(22f);
        titlePaint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));

        Paint labelPaint = new Paint();
        labelPaint.setColor(Color.DKGRAY);
        labelPaint.setTextSize(12f);

        Paint bodyPaint = new Paint();
        bodyPaint.setColor(Color.BLACK);
        bodyPaint.setTextSize(14f);

        Paint linePaint = new Paint();
        linePaint.setColor(Color.LTGRAY);
        linePaint.setStrokeWidth(1f);

        int x = 50;
        int y = 60;

        canvas.drawText("SmartSpend AI — Expense Report", x, y, titlePaint);

        y += 22;
        String generatedOn = new SimpleDateFormat("dd MMM yyyy, HH:mm", Locale.getDefault()).format(new Date());
        canvas.drawText("Period: " + periodLabel + "   ·   Generated on: " + generatedOn, x, y, labelPaint);

        y += 30;
        canvas.drawLine(x, y, PAGE_WIDTH - 50, y, linePaint);

        y += 35;
        Paint totalLabelPaint = new Paint(labelPaint);
        canvas.drawText("TOTAL SPENT", x, y, totalLabelPaint);
        y += 26;
        Paint totalPaint = new Paint(titlePaint);
        totalPaint.setTextSize(28f);
        canvas.drawText(String.format(Locale.getDefault(), "₹%.2f", total), x, y, totalPaint);

        y += 40;
        canvas.drawLine(x, y, PAGE_WIDTH - 50, y, linePaint);

        y += 30;
        Paint sectionHeaderPaint = new Paint(labelPaint);
        sectionHeaderPaint.setTextSize(14f);
        sectionHeaderPaint.setColor(Color.BLACK);
        canvas.drawText("Category Breakdown", x, y, sectionHeaderPaint);
        y += 20;

        if (categoryTotals.isEmpty()) {
            canvas.drawText("No expenses recorded in this period.", x, y, bodyPaint);
        } else {
            for (Map.Entry<String, Double> entry : categoryTotals) {
                canvas.drawText(entry.getKey(), x, y, bodyPaint);
                String amountText = String.format(Locale.getDefault(), "₹%.2f", entry.getValue());
                float amountWidth = bodyPaint.measureText(amountText);
                canvas.drawText(amountText, PAGE_WIDTH - 50 - amountWidth, y, bodyPaint);
                y += 24;
            }
        }

        y += 30;
        canvas.drawLine(x, y, PAGE_WIDTH - 50, y, linePaint);
        y += 20;
        Paint footerPaint = new Paint(labelPaint);
        footerPaint.setTextSize(10f);
        canvas.drawText("Generated by SmartSpend AI — an AI-powered personal finance assistant.", x, y, footerPaint);

        document.finishPage(page);

        File reportsDir = new File(context.getFilesDir(), "reports");
        if (!reportsDir.exists()) {
            reportsDir.mkdirs();
        }

        String fileName = "SmartSpend_Report_" + System.currentTimeMillis() + ".pdf";
        File outputFile = new File(reportsDir, fileName);

        try (FileOutputStream out = new FileOutputStream(outputFile)) {
            document.writeTo(out);
        } finally {
            document.close();
        }

        return outputFile;
    }
}
